routes/web.php
<?php

use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    if(Auth::user()){
        return redirect(route('home'));
    } else {
        return view('welcome');
    }
})->name('welcome');

Route::get('/info', function() {
   phpinfo();
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/books/deleted', 'BookController@showDeleted')->name('books.showDeleted');

Route::resource('books', 'BookController');

Route::post('/books/{book}/restore', 'BookController@restore')->name('books.restore');

Route::resource('users', 'UserController');

resources/views/allBooks.blade.php
@extends('layouts.app')

@section('css')
    <link href="/css/allBooks.css" rel="stylesheet" type="text/css">
@endsection

@section('content')
    <div class="container">
        <div class="content">
            <div class="row">
                <div class="col-md-12">
                    <h3 class="heading">Library</h3>
                    <p>This is your library, where all your uploaded books live.  Click a book to begin playback.</p>
                </div>
            </div>
            <div class="row">
                <div id="book-list">
                    @if($books->isEmpty())
                        <div class="content-empty">
                            <i class="fa fa-bookmark-o" id="book-icon"></i>
                            <h4>There are no books</h4>
                            <br>
                            <a href="{{ route('books.create') }}" class="btn btn-default"><i class="fa fa-upload"></i> Upload New</a>
                        </div>
                    @else
                        @foreach($books as $book)
                            @include('layouts.bookTile')
                        @endforeach
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')

@endsection

resources/views/editBook.blade.php
@extends('layouts.app')

@section('css')
    <link rel="stylesheet" href="/css/editBook.css">
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 upload-form">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="col-xs-6">Upload New Audio File</div>
                                <div class="col-xs-6">
                                    <a href="{{ route('books.index') }}" class="pull-right" id="cancel-button">
                                        <i class="fa fa-chevron-left"></i> Cancel
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="panel-body">
                        <form class="form-horizontal" role="form" method="POST" enctype="multipart/form-data" action="{{ route('books.update', ['id' => $book->id]) }}">
                            {{ csrf_field() }}
                            {{ method_field('PATCH') }}

                            <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                                <label for="title" class="col-md-4 control-label">Title</label>

                                <div class="col-md-6">
                                    <input id="title" type="text" class="form-control" name="title" value="{{ $book->title }}" autofocus>

                                    @if ($errors->has('title'))
                                        <span class="help-block">
                                    <strong>{{ $errors->first('title') }}</strong>
                                </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('author') ? ' has-error' : '' }}">
                                <label for="author" class="col-md-4 control-label">Author</label>

                                <div class="col-md-6">
                                    <input id="author" type="text" class="form-control" name="author" value="{{ $book->author }}">

                                    @if ($errors->has('author'))
                                        <span class="help-block">
                                    <strong>{{ $errors->first('author') }}</strong>
                                </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('imageUpload') ? ' has-error' : '' }}">
                                <label for="imageUpload" class="col-md-4 control-label">Change Cover Image</label>

                                <div class="col-md-6">
                                    <input type="file" name="imageUpload" id="imageUpload">
                                    <p class="help-block">This file will be displayed as artwork for the audio.</p>

                                    @if ($errors->has('imageUpload'))
                                        <span class="help-block">
                                    <strong>{{ $errors->first('imageUpload') }}</strong>
                                </span>
                                    @endif
                                </div>
                            </div>

                            <div class="col-md-4 col-md-offset-5">
                                <div style="background-image: url({{ $book->coverUrl }});" class="book-cover"></div>
                            </div>


                            <div class="form-group">
                                <div class="col-md-8 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                        <i class="fa fa-floppy-o"></i> Save
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('css')
    <link rel="stylesheet" href="/css/home.css">
@endsection

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Welcome, {{ Auth::user()->name }}</div>
                <div class="panel-body">
                    <h5 id="chart-heading">Storage Quota</h5>
                    <canvas id="quota-chart"></canvas>
                    <div class="donut-inner">
                        <h5>{{ $usedSpace['total'] }} / {{ $totalSpace }}</h5>
                        <span>(GB)</span>
                    </div>
                    <div class="col-sm-12" id="welcome-buttons">
                        <a href="{{ route('books.index') }}" class="btn btn-default"><i class="fa fa-bookmark"></i> My Library</a>
                        <a href="{{ route('books.create') }}" class="btn btn-default"><i class="fa fa-upload"></i> Upload New</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.2.2/Chart.js"></script>
    <script>
        var ctx = $("#quota-chart");

        var data = {
            labels: [
                "Library",
                "Deleted",
                "Free"
            ],
            datasets: [
                {
                    data: [{{ $usedSpace['used'] }}, {{ $usedSpace['deleted'] }}, 10],
                    backgroundColor: [
                        "#484e51",
                        "#d3dcde",
                        "#f0f3f4"
                    ],
                    hoverBackgroundColor: [
                        "#484e51",
                        "#d3dcde",
                        "#f0f3f4"
                    ],
                    borderColor: [
                        '#484e51',
                        '#d3dcde',
                        '#f0f3f4'
                    ],
                    borderWidth: 0.1,
                    borderCapStyle: 'round'
                }]
        };

        var options = {
            legend: {
                position: 'bottom',
                display: true
            },
            tooltips: {
                enabled: true
            }
        };

        var chart = new Chart(ctx, {
            type: 'doughnut',
            data: data,
            options: options
        });
    </script>
@endsection

resources/views/showBook.blade.php
@extends('layouts.app')

@section('css')
    <link href="/css/showBook.css" rel="stylesheet" type="text/css">
@endsection

@section('content')
    <div class="container">
        <div class="content">
            <div class="row">
                <div class="col-md-12">
                    <ol class="breadcrumb">
                        <li><a href="{{ route('books.index') }}">Library</a></li>
                        <li class="active">{{ $book->title }}</li>
                    </ol>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4 col-md-offset-4">
                    <div style="background-image: url({{ $book->coverUrl }});" class="book-cover"></div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-8 col-md-offset-2 player">
                    <audio src="{{ $book->streamUrl }}" preload="auto" controls id="player" class="pull-left"></audio>
                    <div class="pull-right buttons">
                            <a href="{{ route('books.edit', ['id' => $book->id]) }}"><i class="fa fa-pencil"></i> Edit</a>

                            <a href="{{ route('books.destroy', ['id' => $book->id])}}"
                               onclick="
                                       event.preventDefault();
                                       if(confirm('Delete {{ $book->title }}?')) {
                                       player.pause();
                                       document.getElementById('delete-form-{{ $book->id }}').submit();
                                       }">
                                <i class="fa fa-trash"></i> Delete
                            </a>

                            <form id="delete-form-{{ $book->id }}" action="{{ route('books.destroy', ['id' => $book->id]) }}" method="POST" style="display: none;">
                                {{ csrf_field() }}
                                {{ method_field('DELETE') }}
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        var player = document.getElementById('player');

        window.onload = function() {
            player.currentTime = {{ $book->position }};
        };

        window.onbeforeunload = function() {
            player.pause();

            $.ajax({
                url: '{{ route('books.savePosition', ['book' => $book->id]) }}',
                type: 'POST',
                data: {
                    position: player.currentTime,
                    _token: "{{ csrf_token() }}"
                }
            });
        };
    </script>
@endsection

resources/views/showDeleted.blade.php
@extends('layouts.app')

@section('css')
    <link href="/css/allBooks.css" rel="stylesheet" type="text/css">
@endsection

@section('content')
    <div class="container">
        <div class="content">
            <div class="row">
                <div class="col-md-12">
                    <h3 class="heading">Deleted Books</h3>
                    <p>Click a book to restore it to your library.  If you run low on storage space, we'll remove these first, starting with the oldest.</p>
                </div>
            </div>
            <div class="row">
                <div id="book-list col-md-12">
                    @if($books->isEmpty())
                        <div class="content-empty">
                            <i class="fa fa-bookmark-o" id="book-icon"></i>
                            <h4>There are no deleted books</h4>
                            <br>
                            <a href="{{ route('books.index') }}" class="btn btn-default"><i class="fa fa-bookmark"></i> My Library</a>
                        </div>
                    @else
                        @foreach($books as $book)
                            @include('layouts.bookTile')
                        @endforeach
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
@endsection

resources/views/uploadBook.blade.php
@extends('layouts.app')

@section('css')
    <link href="/css/uploadBook.css" rel="stylesheet" type="text/css">
@endsection

@section('content')
    <div class="container">
        <div class="content">
            @include('layouts.uploadForm')
        </div>
    </div>
@endsection

@section('script')

@endsection