routes/web.php
<?php

use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    if(Auth::user()){
        return redirect(route('home'));
    } else {
        return view('welcome');
    }
})->name('welcome');

Route::get('/info', function() {
   phpinfo();
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/books/deleted', 'BookController@showDeleted')->name('books.showDeleted');

Route::resource('books', 'BookController');

Route::post('/books/{book}/restore', 'BookController@restore')->name('books.restore');

Route::resource('users', 'UserController');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ Config::get('app.name', 'Ascolto') }}</title>

    <!-- Styles -->
    <link href="/css/app.css" rel="stylesheet">
    <link href="/css/main.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,600" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Slabo+27px:400" rel="stylesheet" type="text/css">
    @yield('css')

    <!-- Scripts -->
    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(),
        ]); ?>
    </script>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <div>
                    <img  class="navbar-logo hidden-xs" src="/img/logo.svg" alt="logo created by Paola Oliani, taken from The Noun Project">
                    @if(Auth::user())
                        <a class="navbar-brand" href="{{ url('/home') }}">
                            {{ Config::get('app.name') }}
                        </a>
                    @else
                        <a class="navbar-brand" href="{{ url('/') }}">
                            {{ Config::get('app.name') }}
                        </a>
                    @endif
                </div>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    &nbsp;
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @if (Auth::guest())
                        <li><a href="{{ url('/login') }}">Login</a></li>
                        <li><a href="{{ url('/register') }}">Register</a></li>
                    @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="{{ route('books.index') }}">
                                        <i class="fa fa-bookmark"></i> My Library
                                    </a>
                                </li>
                                <li>
                                    <a href="{{ route('books.create') }}">
                                        <i class="fa fa-upload"></i> Upload New
                                    </a>
                                </li>
                                <li>
                                    <a href="{{ route('books.showDeleted') }}">
                                        <i class="fa fa-undo"></i> Restore Deleted
                                    </a>
                                </li>
                                <li>
                                    <a href="{{ url('/logout') }}"
                                        onclick="event.preventDefault();
                                                 document.getElementById('logout-form').submit();">
                                        <i class="fa fa-sign-out"></i> Logout
                                    </a>

                                    <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                        {{ csrf_field() }}
                                    </form>
                                </li>
                            </ul>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </nav>

    @yield('content')

    <!-- Scripts -->
    <!-- <script   src="https://code.jquery.com/jquery-3.1.0.min.js"   integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s="   crossorigin="anonymous"></script> -->
    <script src="/js/app.js"></script>
    @yield('script')
</body>
</html>

resources/views/layouts/bookTile.blade.php
<div class="book-container col-md-2">
    @if($book->trashed())
        <form id="restore-form-{{ $book->id }}" action="{{ route('books.restore', ['id' => $book->id]) }}" method="POST" style="display: none;">
            {{ csrf_field() }}
        </form>

        <a href="{{ route('books.restore', $book->id) }} " onclick="
            event.preventDefault();
            if(confirm('Restore {{ $book->title }}?')) {
            document.getElementById('restore-form-{{ $book->id }}').submit();
        }">
            <div style="background-image: url({{ $book->coverUrl }});" class="book-cover"></div>
        </a>
    @else
        <a href="{{ route('books.show', $book->id) }}">
            <div style="background-image: url({{ $book->coverUrl }});" class="book-cover"></div>
        </a>
    @endif
    <div class="book-info">
        <div class="book-title">
            <strong>{{ $book->title }}</strong>,
        </div>
        <div class="book-author">
            {{ $book->author }}
        </div>
    </div>
</div>

resources/views/layouts/error.blade.php
@extends('layouts.app')

@section('css')
    <link href="/css/error.css" rel="stylesheet" type="text/css">
@endsection

@section('content')
    <div class="container">
        <div class="content col-sm-12">
            <div class="title">{{ $exception->getStatusCode() }}</div>
            @yield('error-info')
            <br />
            <a href={{ route('welcome') }}>Home</a>
        </div>
    </div>
@endsection

resources/views/layouts/uploadForm.blade.php
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading">Upload New Audio File</div>
            <div class="panel-body">
                <form class="form-horizontal" role="form" method="POST" enctype="multipart/form-data" action="{{ route('books.store') }}">
                    {{ csrf_field() }}

                    <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                        <label for="title" class="col-md-4 control-label">Title</label>

                        <div class="col-md-6">
                            <input id="title" type="text" class="form-control" name="title" value="{{ old('title') }}" autofocus>

                            @if ($errors->has('title'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('title') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group{{ $errors->has('author') ? ' has-error' : '' }}">
                        <label for="author" class="col-md-4 control-label">Author</label>

                        <div class="col-md-6">
                            <input id="author" type="text" class="form-control" name="author" value="{{ old('author') }}">

                            @if ($errors->has('author'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('author') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group{{ $errors->has('fileUpload') ? ' has-error' : '' }}">
                        <label for="fileUpload" class="col-md-4 control-label">Upload File</label>

                        <div class="col-md-6">
                            <input type="file" name="fileUpload" id="fileUpload" required>
                            <p class="help-block">Currently only MP3 files are supported.</p>

                            @if ($errors->has('fileUpload'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('fileUpload') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group{{ $errors->has('imageUpload') ? ' has-error' : '' }}">
                        <label for="imageUpload" class="col-md-4 control-label">Upload Cover Image</label>

                        <div class="col-md-6">
                            <input type="file" name="imageUpload" id="imageUpload" required>
                            <p class="help-block">This file will be displayed as artwork for the audio.</p>

                            @if ($errors->has('imageUpload'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('imageUpload') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-8 col-md-offset-4">
                            <button type="submit" class="btn btn-primary">
                                <i class="fa fa-upload"></i> Upload
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>